# Generated by Django 2.0.1 on 2018-05-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustask',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
