# Generated by Django 2.0.1 on 2018-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_auto_20180501_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonustask',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='long_description',
            field=models.TextField(blank=True),
        ),
    ]
