# Generated by Django 2.0.1 on 2018-05-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_auto_20180501_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('student_code', models.CharField(max_length=6)),
                ('uniid', models.CharField(max_length=100)),
                ('bonus_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.BonusTask')),
            ],
        ),
    ]
