# Generated by Django 2.0.1 on 2018-05-08 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bonus_task',
        ),
        migrations.AddField(
            model_name='bonustask',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.Student'),
        ),
    ]
