# Generated by Django 2.0.1 on 2018-05-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_auto_20180508_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
