# Generated by Django 2.0.1 on 2018-05-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_student_plagiarism'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kommentaar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
